project:
  type: website

website:
  title: "staromics"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/staromics/
format:
  html:
    theme: yeti
    css: styles.css



